### PR TITLE
add support for (maximize ...) / (minimize ...) commands

### PR DESCRIPTION
**Pull request by OriginLabs-Iguernlala**

### CODE REVIEW

**Comment by Gbury** [comment]
Note: by using lexer keywords for `minimize` and `maximize`, this will make any valid smtlib file that uses these names for regular functions (which seem reasonable to me), become invalid from the point of view of the psmt2 parser, i.e. the psmt2 parser will no longer be able to parse these valid smt2 files...

**Comment by OriginLabs-Iguernlala** [comment]
Right :+1. 

What about this solution ? https://github.com/OriginLabs-Iguernlala/psmt2-frontend/commit/d5b55dab5c34b4b9659c4b8eac4908e013e92b71

**Comment by Gbury** [comment]
It's a bit hack-ish, but at least it shouldn't affect valid smtlib-2 files, ^^

**Comment by ACoquereau** [comment]
> Right :+1.
> 
> What about this solution ? [OriginLabs-Iguernlala@d5b55da](https://github.com/OriginLabs-Iguernlala/psmt2-frontend/commit/d5b55dab5c34b4b9659c4b8eac4908e013e92b71)

This solution sounds better

**Comment by OriginLabs-Iguernlala** [comment]
Replaced by https://github.com/ACoquereau/psmt2-frontend/pull/17/files.

**Pull request closed without merging**
